package it.unige.dibris.adm;
//Represent the standard object generated by classification


import java.util.List;

import edu.mit.jwi.item.POS;

public class ClassifierObject {
	private List<String> textWords;
	private String lemmaWord;
	private String ontologyWord;
	private POS pos;
	private List<String> ontologyTree;
	
	public ClassifierObject (List<String> t, String l, String o, POS p, List<String> ontologyTree) {
		this.textWords = t;
		this.lemmaWord = l;
		this.ontologyWord = o;
		this.pos = p;
		this.ontologyTree = ontologyTree;
	}

	public String getLemmaWord() {
		return lemmaWord;
	}


	public void setLemmaWord(String lemmaWord) {
		this.lemmaWord = lemmaWord;
	}


	public POS getPos() {
		return pos;
	}

	public void setPos(POS pos) {
		this.pos = pos;
	}

	public List<String> getTextWords() {
		return textWords;
	}

	public void setTextWords(List<String> textWords) {
		this.textWords = textWords;
	}
	
	public void addTextWord(String word){
		this.textWords.add(word);
	}

	public String getOntologyWord() {
		return ontologyWord;
	}

	public void setOntologyWord(String ontologyWord) {
		this.ontologyWord = ontologyWord;
	}

	public int getNumberOfOcc() {
		return textWords.size();
	}

	public List<String> getOntologyTree() {
		return ontologyTree;
	}

	public void setOntologyTree(List<String> ontologyTree) {
		this.ontologyTree = ontologyTree;
	}
	
	@Override
	public String toString() {
		return textWords + "\t " + ontologyWord + " \t" + 
				textWords.size() + " \t " + ontologyTree.toString();
	}
}
